"""
User Router — Personalized content history and profile data.
Follows CODING_STANDARDS.md: Service-Driven Pattern.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Dict, Any

from app.database import get_db
from app.dependencies import get_current_user
from app.services.campaign_service import CampaignService
from app.services.script_service import ScriptService
from app.services.video_service import VideoService
from app.models.image import GeneratedImage

router = APIRouter(prefix="/api/user", tags=["User Profile"])

@router.get("/profile")
def get_user_profile(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Aggregates all content generated by the current user across services."""
    email = current_user.get("email")
    if not email:
        raise HTTPException(status_code=400, detail="User identity not found in token.")

    # 🚀 Parallelized Service Access
    campaigns = CampaignService(db).list_campaigns(user_email=email)
    scripts = ScriptService().get_history(db, user_email=email)
    videos = VideoService(db).list_videos(user_email=email)
    images = db.query(GeneratedImage).filter(GeneratedImage.user_email == email).order_by(GeneratedImage.created_at.desc()).all()

    return {
        "email": email,
        "campaigns": campaigns,
        "scripts": scripts,
        "videos": videos,
        "images": images
    }

@router.get("/history")
def get_user_history(
    type: str,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Fetch specific filtered history for the current user."""
    email = current_user.get("email")
    if not email:
        raise HTTPException(status_code=400, detail="User identity not found in token.")

    # Strategy Pattern for history lookup
    lookup = {
        "campaign": lambda: CampaignService(db).list_campaigns(user_email=email),
        "script":   lambda: ScriptService().get_history(db, user_email=email),
        "video":    lambda: VideoService(db).list_videos(user_email=email),
        "image":    lambda: db.query(GeneratedImage).filter(GeneratedImage.user_email == email).order_by(GeneratedImage.created_at.desc()).all()
    }

    if type not in lookup:
        raise HTTPException(status_code=400, detail=f"Invalid history type: {type}")

    return lookup[type]()
